Implement submodules per unique scene
DragonRidersUnite/scale pull request #10
Opened 2024-05-20 07:10 UTC by Anthogonyst

As per issue #8 , I created an internal module so that each scene has a generic tick method and an unique namespace. Cheers.

2024-05-20 12:06 UTC, brettchalupa requested changes
Thanks for this contribution! Looking good to me. One minor request for all of the changed files for formatting.

2024-05-20 12:06 UTC, brettchalupa commented on app/scenes/gameplay.rb
> +module GameplayScene
Would you mind indenting all of these modules and their associated code one level? It'll make it easier to know it's a submodule of `Scene`

2024-05-21 05:25 UTC, Anthogonyst commented on app/scenes/gameplay.rb
> +module GameplayScene
I did that at first, but afterwards git kind of mangled the changes a little bit in a disruptive way. So it looks like the whole file gets replaced when it's not supposed to. It breaks git blame and so on. Any suggestions how to proceed?

2024-06-07 12:41 UTC, brettchalupa commented on app/scenes/gameplay.rb
> +module GameplayScene
@Anthogonyst you should be able to indent it, commit those changes, and it should be all set! Let me know if you want any support with that. Thanks!

2024-06-26 07:55 UTC, closed without merging